language: python
python:
  - "3.6"

services:
  - docker
before_install:
  - echo 123456789 | docker login --username "daltonbigirimana5" --password-stdin

before_script: pip install docker-compose

script:
    - docker-compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test && flake8"